spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

build:
  version: "unknown-version"

contact:
  support:
    email: "info@company.com"
    phone: "0000000000"
