management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh, shutdown
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

build:
  version: "unknown-version"

contact:
  support:
    email: "info@company.com"
    phone: "0000000000"
